package com.baseframework.domain.security.access;

// Generated Jan 2, 2010 12:14:16 AM by Hibernate Tools 3.2.2.GA

import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Module generated by hbm2java
 */
public class Module implements java.io.Serializable {

	private int moduleId;
	
	private String moduleName;	
	
	private Set<Function> functions = null;

	public Module() {
	}

	public Module(String moduleName) {
		this.moduleName = moduleName;
	}

	public Module(String moduleName, Set<Function> functions) {
		this.moduleName = moduleName;
		this.functions = functions;
	}

	public int getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(int moduleId) {
		this.moduleId = moduleId;
	}

	public String getModuleName() {
		return this.moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	public Set<Function> getFunctions() {
		return this.functions;
	}

	@JsonIgnore
	public void setFunctions(Set<Function> functions) {
		this.functions = functions;
	}

	public String toString() {
		return this.moduleId + "-" + this.moduleName;
	}

}
